### PR TITLE
Update to 1.12

### PR DESCRIPTION
**Pull request by GitHubLynx**
- Changed from VertexBuffer to BufferBuilder
- Some method mapping and field mapping changes in Forge
- Parameter added to drawButton in 1.12

Only the necessary stuff for using it in 1.12.

### CODE REVIEW

**Comment by xPatrykPlayX** [comment]
When schematica mod and Lunatrius be update to 1.12 Minecraft version?

**Comment by GitHubLynx** [comment]
Check here: https://github.com/Lunatrius/Schematica/pull/229

**Comment by danner** [comment]
Is there a compiled build of this PR to test out?

**Comment by GitHubLynx** [comment]
Yup! It also contains the Schematica plugin but should be fine.

https://github.com/Lunatrius/Schematica/files/1105169/Schematica-1.12-1.7.8.zip

**Comment by Lunatrius** [comment]
0da969921b849a130ef68045af85ed1afebcd776 closes this. Thanks for your early effort!

**Pull request closed without merging**
